---
- name: Configure IIS web server
  hosts: win1.example.com
  tasks:

    - name: Install IIS package.
      win_feature:
        name: Web-Server
        state: present


    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started


    - name: Create a web page
      win_copy:
        content: "Hello, This is a test web page."
        dest: C:\Inetpub\wwwroot\index.html
